In [1]:
import numpy as np 
import pandas as pd

train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

print(train.shape, test.shape)

(4209, 378) (4209, 377)

In [2]:
train.head()

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,a,d,u,j,o,...,0,0,1,0,0,0,0,0,0,0
1,6,88.53,k,t,av,e,d,y,l,o,...,1,0,0,0,0,0,0,0,0,0
2,7,76.26,az,w,n,c,d,x,j,x,...,0,0,0,0,0,0,1,0,0,0
3,9,80.62,az,t,n,f,d,x,l,e,...,0,0,0,0,0,0,0,0,0,0
4,13,78.02,az,v,n,f,d,h,d,n,...,0,0,0,0,0,0,0,0,0,0

In [3]:
test.head()

,ID,X0,X1,X2,X3,X4,X5,X6,X8,X10,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,1,az,v,n,f,d,t,a,w,0,...,0,0,0,1,0,0,0,0,0,0
1,2,t,b,ai,a,d,b,g,y,0,...,0,0,1,0,0,0,0,0,0,0
2,3,az,v,as,f,d,a,j,j,0,...,0,0,0,1,0,0,0,0,0,0
3,4,az,l,n,f,d,z,l,n,0,...,0,0,0,1,0,0,0,0,0,0
4,5,w,s,as,c,d,y,i,m,0,...,1,0,0,0,0,0,0,0,0,0

In [4]:
from sklearn.preprocessing import LabelEncoder

for c in train.columns:
    if train[c].dtype == 'object':
        le = LabelEncoder() 
        le.fit(list(train[c].values) + list(test[c].values)) 
        train[c] = le.transform(list(train[c].values))
        test[c] = le.transform(list(test[c].values))

In [5]:
train.head()

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,37,23,20,0,3,27,9,14,...,0,0,1,0,0,0,0,0,0,0
1,6,88.53,37,21,22,4,3,31,11,14,...,1,0,0,0,0,0,0,0,0,0
2,7,76.26,24,24,38,2,3,30,9,23,...,0,0,0,0,0,0,1,0,0,0
3,9,80.62,24,21,38,5,3,30,11,4,...,0,0,0,0,0,0,0,0,0,0
4,13,78.02,24,23,38,5,3,14,3,13,...,0,0,0,0,0,0,0,0,0,0

In [6]:
X_train = train.drop(['y', 'ID'], axis=1)
X_test = test.drop(['ID'], axis=1)
y_train = train['y']

In [7]:
from sklearn.decomposition import PCA, FastICA, TruncatedSVD
from sklearn.random_projection import GaussianRandomProjection
from sklearn.random_projection import SparseRandomProjection

pca = PCA(n_components=5)
ica = FastICA(n_components=5, max_iter=1000)
tsvd = TruncatedSVD(n_components=5)
gp = GaussianRandomProjection(n_components=5)
sp = SparseRandomProjection(n_components=5, dense_output=True)

X_train_pca = pd.DataFrame(pca.fit_transform(X_train))
X_train_ica = pd.DataFrame(ica.fit_transform(X_train))
X_train_tsvd = pd.DataFrame(tsvd.fit_transform(X_train))
X_train_gp = pd.DataFrame(gp.fit_transform(X_train))
X_train_sp = pd.DataFrame(sp.fit_transform(X_train))

X_test_pca = pd.DataFrame(pca.transform(X_test))
X_test_ica = pd.DataFrame(ica.transform(X_test))
X_test_tsvd = pd.DataFrame(tsvd.transform(X_test))
X_test_gp = pd.DataFrame(gp.transform(X_test))
X_test_sp = pd.DataFrame(sp.transform(X_test))

In [8]:
X_train_pca.columns = ['pca_{}'.format(i) for i in X_train_pca.columns]
X_train_ica.columns = ['ica_{}'.format(i) for i in X_train_ica.columns]
X_train_tsvd.columns = ['tsvd_{}'.format(i) for i in X_train_tsvd.columns]
X_train_gp.columns = ['gp_{}'.format(i) for i in X_train_gp.columns]
X_train_sp.columns = ['sp_{}'.format(i) for i in X_train_sp.columns]

X_train = pd.concat((X_train, X_train_pca), axis=1)
X_train = pd.concat((X_train, X_train_ica), axis=1)
X_train = pd.concat((X_train, X_train_tsvd), axis=1)
X_train = pd.concat((X_train, X_train_gp), axis=1)
X_train = pd.concat((X_train, X_train_sp), axis=1)

X_train.head()

,X0,X1,X2,X3,X4,X5,X6,X8,X10,X11,...,gp_0,gp_1,gp_2,gp_3,gp_4,sp_0,sp_1,sp_2,sp_3,sp_4
0,37,23,20,0,3,27,9,14,0,0,...,-11.565051,-33.727235,-2.010576,-2.343510,-24.065625,0.0000,-1.969300,1.9693,-1.9693,-3.938601
1,37,21,22,4,3,31,11,14,0,0,...,-12.028696,-37.470568,-9.524633,-3.692309,-28.618919,0.0000,-1.969300,1.9693,0.0000,0.000000
2,24,24,38,2,3,30,9,23,0,0,...,-4.947723,-12.708614,-11.120667,31.121624,-32.597908,0.0000,-7.877201,0.0000,0.0000,1.969300
3,24,21,38,5,3,30,11,4,0,0,...,-6.577652,-24.102886,-11.015814,27.949644,-27.964476,0.0000,-7.877201,0.0000,1.9693,3.938601
4,24,23,38,5,3,14,3,13,0,0,...,7.556111,-11.095553,-13.578201,38.555910,-20.639547,-1.9693,-7.877201,0.0000,-1.9693,3.938601

In [9]:
X_test_pca.columns = ['pca_{}'.format(i) for i in X_test_pca.columns]
X_test_ica.columns = ['ica_{}'.format(i) for i in X_test_ica.columns]
X_test_tsvd.columns = ['tsvd_{}'.format(i) for i in X_test_tsvd.columns]
X_test_gp.columns = ['gp_{}'.format(i) for i in X_test_gp.columns]
X_test_sp.columns = ['sp_{}'.format(i) for i in X_test_sp.columns]

X_test = pd.concat((X_test, X_test_pca), axis=1)
X_test = pd.concat((X_test, X_test_ica), axis=1)
X_test = pd.concat((X_test, X_test_tsvd), axis=1)
X_test = pd.concat((X_test, X_test_gp), axis=1)
X_test = pd.concat((X_test, X_test_sp), axis=1)

X_test.head()

,X0,X1,X2,X3,X4,X5,X6,X8,X10,X11,...,gp_0,gp_1,gp_2,gp_3,gp_4,sp_0,sp_1,sp_2,sp_3,sp_4
0,24,23,38,5,3,26,0,22,0,0,...,-3.747952,-9.603231,-18.762137,37.110667,-21.336583,-1.9693,-7.877201,0.0000,-1.9693,3.938601
1,46,3,9,0,3,9,6,24,0,0,...,-8.151758,-26.848249,3.473393,-19.346397,-14.324191,1.9693,-1.969300,1.9693,-1.9693,0.000000
2,24,23,19,5,3,0,9,9,0,0,...,18.860398,-12.164879,-2.672260,21.891901,-16.476394,0.0000,-3.938601,1.9693,1.9693,1.969300
3,24,13,38,5,3,32,11,13,0,0,...,-15.645327,-15.385439,-11.992394,22.892834,-28.921779,-1.9693,-7.877201,0.0000,-1.9693,3.938601
4,49,20,19,2,3,31,8,12,0,0,...,-12.716109,-52.244389,-8.248150,-9.344637,-26.909281,1.9693,-1.969300,0.0000,1.9693,1.969300

In [15]:
from bayes_opt import BayesianOptimization
from sklearn.metrics import r2_score
import xgboost as xgb

def xgb_r2_score(preds, dtrain):
    labels = dtrain.get_label()
    return 'r2', r2_score(labels, preds)

def eval_xgb(max_depth, subsample, min_child_weight, gamma, colsample_bytree):
    xgb_params = {'n_trees': 550, 
                  'eta': 0.008, 
                  'max_depth': int(max_depth), 
                  'subsample': max(min(subsample, 1), 0), 
                  'objective': 'reg:linear', 
                  'base_score': np.mean(y_train), 
                  'silent': 1, 
                  'min_child_weight': int(min_child_weight), 
                  'gamma': max(gamma, 0), 
                  'colsample_bytree': max(min(colsample_bytree, 1), 0)}
    
    scores = xgb.cv(xgb_params, dtrain, num_boost_round=1500, 
                    early_stopping_rounds=50, verbose_eval=False, 
                    feval=xgb_r2_score, maximize=True, nfold=5)['test-r2-mean'].iloc[-1]
    return scores

In [16]:
params = {'min_child_weight': (1, 20), 
          'gamma': (0, 10), 
          'subsample': (0.5, 1), 
          'colsample_bytree': (0.1, 1), 
          'max_depth': (2, 15)}

dtrain = xgb.DMatrix(X_train, y_train)
dtest = xgb.DMatrix(X_test)

xgb_bayesopt = BayesianOptimization(eval_xgb, params)
xgb_bayesopt.maximize(init_points=5, n_iter=2)

Initialization
---------------------------------------------------------------------------------------------------------------
 Step |   Time |      Value |   colsample_bytree |     gamma |   max_depth |   min_child_weight |   subsample |
    1 | 01m49s |    0.55022 |             0.8605 |    8.6238 |     11.9130 |            19.5141 |      0.6586 |
    2 | 01m25s |    0.55183 |             0.8772 |    0.0969 |      9.1413 |             8.7790 |      0.5073 |
    3 | 00m45s |    0.55979 |             0.3615 |    6.7352 |      6.6393 |            11.3553 |      0.7245 |
    4 | 01m13s |    0.55081 |             0.6846 |    1.5313 |      9.2580 |            10.5734 |      0.8578 |
    5 | 00m41s |    0.53511 |             0.1868 |    8.0376 |     13.5053 |            13.0834 |      0.9506 |
Bayesian Optimization
---------------------------------------------------------------------------------------------------------------
 Step |   Time |      Value |   colsample_bytree |     gamma |   max_depth |   min_child_weight |   subsample |
    6 | 01m21s |    0.55961 |             0.1000 |    0.0000 |      2.0000 |            20.0000 |      0.5000 |
    7 | 01m19s |    0.56823 |             1.0000 |   10.0000 |      2.0000 |             1.0000 |      0.5000 |

In [26]:
p = xgb_bayesopt.res['max']['max_params']

xgb_params = {'n_trees': 550, 
              'eta': 0.008, 
              'max_depth': int(p['max_depth']), 
              'subsample': max(min(p['subsample'], 1), 0), 
              'objective': 'reg:linear', 
              'base_score': np.mean(y_train), 
              'silent': 1, 
              'min_child_weight': int(p['min_child_weight']), 
              'gamma': max(p['gamma'], 0), 
              'colsample_bytree': max(min(p['colsample_bytree'], 1), 0)}

bst = xgb.train(xgb_params, dtrain, num_boost_round=1500, 
                verbose_eval=False, feval=xgb_r2_score, maximize=True)

print(round(r2_score(dtrain.get_label(), bst.predict(dtrain)), 2))

0.62

In [27]:
y_pred = bst.predict(dtest)

output = pd.DataFrame({'id': test['ID'].astype(np.int32), 'y': y_pred})
output.to_csv('submission.csv', index=False)